---
- name: Install Heimdall
  become: true
  tags: install
  block:

    - name: Add heimdall group
      ansible.builtin.group:
        name: heimdall
        state: present

    - name: Add Ansible user to heimdall
      ansible.builtin.user:
        name: "{{ user }}"
        groups: heimdall
        append: true

    - name: Add heimdall user
      ansible.builtin.user:
        name: heimdall
        group: heimdall

    - name: Create heimdall config directory
      ansible.builtin.file:
        path: /home/heimdall/config
        state: directory
        mode: "770"
        owner: heimdall
        group: heimdall

    - name: Instantiate passwd database
      getent:
        database: passwd

    - name: Create Heimdall container
      community.docker.docker_container:
        name: heimdall
        image: lscr.io/linuxserver/heimdall:latest
        pull: true
        restart_policy: unless-stopped
        volumes:
          - /home/heimdall/config:/config
        networks:
          - name: proxy_net
        env:
          TZ: Asia/Bangkok
          PUID: "{{ getent_passwd['heimdall'].1 }}"
          PGID: "{{ getent_passwd['heimdall'].2 }}"
