---
- name: Install Heimdall
  become: true
  tags: install
  block:

    - name: Create heimdall_config volume
      docker_volume:
        driver: "local"
        driver_options:
          type: nfs
          o: "addr={{ nas }},nolock,soft,rw"
          device: "{{ heimdall_config_nfs }}"
        volume_name: heimdall_config

    - name: Create Heimdall container
      community.docker.docker_container:
        name: heimdall
        image: lscr.io/linuxserver/heimdall:latest
        pull: true
        restart_policy: unless-stopped
        volumes:
          - heimdall_config:/config
        networks:
          - name: proxy_net
        env:
          TZ: Asia/Bangkok
          PUID: "{{ heimdall_uid }}"
          PGID: "{{ heimdall_gid }}"
